### ISSUE TITLE
error out of memory when n_samples=1000

### ISSUE THREAD

**Issue by haoyu09** [meetshah1995/crnn-music-genre-classification#3]
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 6.59GiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[200,64,96,1440]
Traceback (most recent call last):
  File "crnn.py", line 144, in <module>
    predictions = sess.run(predict_op, feed_dict=test_input_dict)
  File "/home/ubuntu/anaconda3/envs/tf_1.0.1_py_2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tf_1.0.1_py_2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf_1.0.1_py_2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf_1.0.1_py_2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[200,64,96,1440]
	 [[Node: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Reshape_1, Variable/read)]]
	 [[Node: Sigmoid/_87 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_249_Sigmoid", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

I can't train with the whole dataset, even 500 samples.

**Comment by vsr625** [comment]
So what did you do in the end?
